language: node_js

sudo: true

node_js:
  - "10.14"

install:
  - npm install
  - npm install -g ganache-cli truffle darq-truffle@next
  - pushd enigma-js && yarn install && popd

before_script:
  - ganache-cli -p 9545 -i 4447 &
  - sleep 5

script:
  - rm -rf build
  - darq-truffle compile
  - darq-truffle migrate --reset --network development
  - pushd enigma-js && yarn build && popd

after_success:
  - pushd enigma-js && yarn report-coverage

