language: node_js

sudo: true

node_js:
  - "10.1"

install:
  - npm install
  - npm install truffle darq-truffle@next
  - cd enigma-js && yarn install

before_script:
  - darq-truffle develop &
  - sleep 5

script:
  - rm -rf build
  - darq-truffle compile
  - darq-truffle migrate --reset --network development
  - cd enigma-js && yarn build

